# Generated by Django 3.0.4 on 2020-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageservice', '0003_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created',
        ),
    ]
